config/routes.rb
Rails.application.routes.draw do
  post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
  post 'line_items' => 'line_items#create'
  get 'line_items/:id' => 'line_items#show', as: 'line_item'
  delete 'line_items/:id' => 'line_items#destroy'
  resources :carts
  resources :line_items
  resources :orders
  resources :user
  resources :products do
    resources :reviews
  end

  devise_for :users

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def sub_total
    sum = 0
    line_items.each do |line_item|
      line_item.quantity = 1 if line_item.quantity.nil?
      sum += line_item.total_price
    end
    sum
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    quantity * product.price unless quantity.nil?
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  has_many :reviews, dependent: :destroy
  has_many :line_items, dependent: :destroy

  has_one_attached :attached_image, dependent: :destroy

  after_save :assign_sr_no

  private

  def assign_sr_no
    self.serial_no = "Prd-#{id}"
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :reviews

  attr_accessor :first_name, :last_name

  before_save :set_fullname

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  private

  def set_fullname
    self.full_name = "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :current_cart

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:first_name, :last_name, :email, :password)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:first_name, :last_name, :email, :password, :current_password)
    end
  end

  private

  def current_cart
    if session[:cart_id]
      cart = Cart.find_by(id: session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end

    if session[:cart_id].nil?
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[show destroy]
  def show; end

  def destroy
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

  private

  def set_cart
    @cart = @current_cart
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[destroy add_quantity reduce_quantity]
  def index; end

  def create
    chosen_product = Product.find(params[:product_id])
    current_cart = @current_cart
    if current_cart.products.include?(chosen_product)
      @line_item = current_cart.line_items.find_by(product_id: chosen_product)
      @line_item.quantity = 0 if @line_item.quantity.nil?
      @line_item.quantity += 1
    else
      @line_item = LineItem.new
      @line_item.cart = current_cart
      @line_item.product = chosen_product
    end
    @line_item.save!
    redirect_to cart_path(current_cart)
  end

  def destroy
    @line_item.destroy
    redirect_to cart_path(@current_cart)
  end

  def add_quantity
    @line_item.quantity = 0 if @line_item.quantity.nil?
    @line_item.quantity += 1
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  def reduce_quantity
    @line_item.quantity -= 1 if @line_item.quantity > 1
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  private

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  def line_item_params
    params.require(:line_item).permit(:quantity, :product_id, :cart_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show]
  before_action :set_owned_product, only: %i[edit update destroy]

  def index
    @products = Product.order(updated_at: :desc)
  end

  def create
    @product = current_user.products.create(product_params)
    redirect_to products_path, notice: 'Product was successfully created.' if @product.save!
  end

  def new
    @product = current_user.products.new
  end

  def show; end

  def update
    if @product.update(product_params)
      redirect_to products_path, notice: 'Product was successfully Updated.'
    end
  end

  def destroy
    redirect_to products_path, notice: 'Product was successfully deleted.' if @product.destroy
  end

  private

  def set_owned_product
    @product = current_user.products.find(params[:id])
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:serial_no, :attached_image, :title, :description, :price)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_current, only: %i[show update edit destroy create]
  before_action :set_review, only: %i[update edit destroy]

  def index; end

  def new
    @review = current_user.product.reviews.new
  end

  def create
    @product.reviews.create(review_params.merge(author_name: current_user.email,
                                                user_id: current_user.id))

    redirect_to product_path(@product)
  end

  def update; end

  def destroy; end

  def show; end

  private

  def set_current
    @product = Product.find(params[:product_id])
    if @product.user_id == current_user.id
      redirect_to product_path(@product), notice: 'Please dont try to add fake reviews'
    end
  end

  def set_review
    @review = @product.reviews.find(params[:review_id])
    if @review.user_id != current_user.id
      redirect_to product_path(@product), notice: 'You are not authorize'
    end
  end

  def review_params
    params.require(:product).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/carts/show.html.erb
<h2>Cart show</h2>
<ul>
  <% @cart.line_items.each do |line_item| %>
    <li>Item: <%= line_item.product.title %>/ Price: <%= number_to_currency(line_item.product.price) %>/ Quantity: <%= line_item.quantity %>/ Total Price: <%= number_to_currency(line_item.total_price) %>
    <ul>
      <li>
        <%= link_to "Add one", line_item_add_path(id: line_item), method: :post %>
        <%= link_to "Reduce one", line_item_reduce_path(id: line_item), method: :post %>
      </li>
      <li>
        <%= link_to "Remove item", line_item_path(line_item), method: :delete %>
      </li>
    </ul>
  <% end %>
</ul>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>
<%= link_to "Proceed to checkout", new_order_path %><br>
<%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"}%>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Daraz.pk", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if user_signed_in? %>
       <%=  link_to "Products", products_path, class: "nav-link"%>
        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daraz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "home/header" %>
    <%if notice%>
      <%= render "layouts/alerts" %>
    <%end%>
    <br/>
     <%= yield %>
  </body>
</html>

app/views/line_items/index.html.erb
 <%= link_to "Add one", line_item_add_path(:id => line_item), method: :post %>
        <%= link_to "Reduce one", line_item_reduce_path(:id => line_item), method: :post %>

        <%= link_to "Remove item", line_item_path(line_item), method: :delete %>

app/views/products/_form.html.erb
<div class="form">
  <%= form_with(model: product) do |form| %>
    <div class="field form-group">
      <%= form.text_field :title, class: "form-control", placeholder: 'Title'%>
    </div>
    <div class="field form-group">
      <%= form.text_field :price, class: "form-control", placeholder: 'Price in USD'%>
    </div>
    <div class="field form-group">
      <%= form.text_area :description, class: "form-control", placeholder: "Description"%>
    </div>
     <div class="field form-group">
      <%= form.file_field :attached_image, class: "form-control", placeholder: 'Image'%>
    </div>
    <div class="actions">
      <%= form.submit class: 'btn btn-secondary'%>
    </div>
  <% end %>
</div>

app/views/products/_review.html.erb
<div>
  <h4>Review by <%= review.author_name %></h4>
  <p class="review"><%= review.body %></p>
</div>

app/views/products/edit.html.erb
<div class="container">
  <h1>Editing product</h1>

  <%= render 'form', product: @product %>
  <br />

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<%= link_to 'New product', new_product_path() %>
<div class="container">
<div class="card-deck">
  <% @products.each do |product| %>

    <div class=" row">
      <div class="col-lg-6 mb-4">
        <div class="card " style="width:400px">
          <%= link_to image_tag product.attached_image , class: 'img-fluid' if product.attached_image.attached? %>
          <div class="card-body">
            <h4 class="card-title"><%= product.title %></h4>
            <% description=product.description %>
            <p class="card-text"><%= description%></p>
            <p><%= product.price %> USD</p>
              <%= link_to 'Show', product, class: 'btn btn-secondary' %>
              <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-secondary' %>
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary' %>

          </div>
        </div>
      </div>
    </div>
  <% end %>
 </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1>New product</h1>
  <span>
  <%= render 'form', product: @product %>
  <br />
  <%= link_to 'Back', products_path, class: "btn btn-secondary"%>
  </span>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="jumbotron">
    <%= link_to image_tag @product.attached_image , class: 'img-fluid' if @product.attached_image.attached? %>
    <h1 class="display-6"><%= @product.title %></h1>
    <p class="lead"><%= @product.description %></p>
    <p class="lead"><%= @product.price %> USD</p>
    <%= button_to "Add #{@product.title} to cart", line_items_path(:product_id => @product.id) %>
    <%= link_to 'Back', products_path, class:"btn btn-secondary" %> |
    <%= link_to 'Edit', edit_product_path(@product), class:"btn btn-secondary" %>

    <h3>Reviews</h3>
    <%= render partial: 'products/review', collection: @product.reviews.reverse %>
    <%= render partial: 'reviews/form' %>
  </div>
</div>

app/views/reviews/_form.html.erb
<button class="btn btn-secondary mt-2" style="width:100%" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Post Review
</button>

<div class="collapse" id="collapseExample">
  <div class="card card-body">
    <div class="form">
      <%= form_for( [@product, @product.reviews.build], as: :product, url: product_reviews_path(@product)) do |f| %>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", placeholder: "Give feedback here!"%>
          </div>
          <div class="form-group">
            <%= f.submit class: 'btn btn-secondary'%>
          </div>
      <% end %>
    </div>
  </div>
<div>

</div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>New product</h1>
  <span>
  <%= render 'form', product: @product %>
  <br />
  <%= link_to 'Back', products_path, class: "btn btn-secondary"%>
  </span>
</div>